name: "postgres"
services:
  postgres:
    container_name: psql
    image: "postgres:16"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:

networks:
  backend:
    name: backend